#!/usr/bin/env bash
# node/snapshot.sh -- capture node state for later comparison. RUNS ON A LEASED NODE.
#
# Taken before install ("pre") and after teardown ("post"). bin/k8s-verify-clean
# diffs the two and fails loudly on drift. This is what turns "we left the node
# pristine" from a claim into a test.
#
# Read-only apart from writing the snapshot itself. Uses sudo only for privileged
# reads; output files are written by the invoking user via shell redirection, so
# they land on NFS owned by us rather than by root.
#
# usage: node/snapshot.sh --outdir <dir> [--phase pre|post]

set -uo pipefail

OUTDIR="" PHASE="pre"
while (($#)); do
  case "$1" in
    --outdir) OUTDIR="${2:?}"; shift 2 ;;
    --phase)  PHASE="${2:?}";  shift 2 ;;
    *) printf 'unknown argument: %s\n' "$1" >&2; exit 2 ;;
  esac
done
[[ -n "$OUTDIR" ]] || { printf -- '--outdir is required\n' >&2; exit 2; }

NODE_LOCAL_DISK="${NODE_LOCAL_DISK:-/mnt/localdisk}"
HOST_CDI_SPEC="${HOST_CDI_SPEC:-/var/run/cdi/nvidia.yaml}"

mkdir -p "$OUTDIR"

# cap <file> <cmd...> -- capture a command's output, tolerating failure.
cap() { local f="$1"; shift; "$@" >"${OUTDIR}/${f}" 2>/dev/null || : ; }

printf '%s\n' "$PHASE" > "${OUTDIR}/phase"
{ printf 'node=%s\n' "$(hostname)"
  printf 'phase=%s\n' "$PHASE"
  printf 'taken=%s\n' "$(date -Is)"
  printf 'kernel=%s\n' "$(uname -r)"
} > "${OUTDIR}/meta"

# ---------------------------------------------------------------- firewall
# iptables-save omits counters by default, so output is stable across runs and
# safe to diff. Any KUBE-/CNI-/cilium chain appearing in "post" is our leftovers.
# Normalize before storing, or every snapshot "drifts" against itself:
#   - "# Generated by ... on <date>" / "# Completed on <date>" comment lines
#   - packet/byte counters in ":CHAIN POLICY [pkts:bytes]" policy lines
# Chain and rule structure is what we actually care about.
_norm_ipt() { grep -v '^#' | sed -E 's/\[[0-9]+:[0-9]+\]//g'; }
sudo -n iptables-save  2>/dev/null | _norm_ipt > "${OUTDIR}/iptables.txt"  || :
sudo -n ip6tables-save 2>/dev/null | _norm_ipt > "${OUTDIR}/ip6tables.txt" || :
cap iptables.raw sudo -n iptables-save
# nftables rulesets carry volatile handles; kept for humans, excluded from diffs.
cap nftables.raw  sudo -n nft list ruleset

# ---------------------------------------------------------------- networking
# Strip the volatile bits: veth/cilium/cni interfaces are what we're hunting for,
# but MAC-derived IPv6 link-local addresses and flags churn on their own.
ip -br link show 2>/dev/null | awk '{print $1}' | sed 's/@.*//' | sort > "${OUTDIR}/interfaces.txt"
cap addr.raw  ip -br addr
# Sort for stability, and drop the RA lease countdown on IPv6 routes, which
# ticks down every second.
ip route    2>/dev/null | sort                                > "${OUTDIR}/route.txt"  || :
ip -6 route 2>/dev/null | sed -E 's/ expires [0-9]+sec//' | sort > "${OUTDIR}/route6.txt" || :

# ---------------------------------------------------------------- mounts
# Sort for stable diffing; mount order is not meaningful.
awk '{print $2" "$3}' /proc/self/mounts 2>/dev/null | sort > "${OUTDIR}/mounts.txt"

# ---------------------------------------------------------------- listening ports
# Two forms: a normalized one for diffing, and the raw one with PIDs for humans.
# PIDs change on every restart, so they must not participate in the diff.
# Exclude the ephemeral range: those are transient client sockets that differ on
# every run and would show up as phantom drift. Only service ports matter here.
_eph_lo="$(awk '{print $1}' /proc/sys/net/ipv4/ip_local_port_range 2>/dev/null || echo 32768)"
sudo -n ss -Hltn 2>/dev/null \
  | awk '{print $4}' | sed 's/.*://' \
  | awk -v lo="${_eph_lo:-32768}" '$1+0 > 0 && $1+0 < lo' \
  | sort -un | paste -sd, > "${OUTDIR}/ports.txt"
cap ports.raw sudo -n ss -ltnp

# ---------------------------------------------------------------- systemd
# Only units we could plausibly affect, plus anything k8s-shaped that appears.
{ for u in nvidia-imex nvidia-dcgm dcgm-exporter nvidia-persistenced \
           containerd docker slurmd; do
    printf '%s enabled=%s active=%s\n' "$u" \
      "$(systemctl is-enabled "$u" 2>/dev/null || echo n/a)" \
      "$(systemctl is-active  "$u" 2>/dev/null || echo n/a)"
  done
} > "${OUTDIR}/services.txt"

systemctl list-units --all --no-legend --plain 'k3s*' 'kubelet*' 'cilium*' 2>/dev/null \
  | awk '{print $1}' | sort > "${OUTDIR}/k8s-units.txt"

# ---------------------------------------------------------------- gpu / cdi
# The host owns this spec. Hash it, and keep a copy so teardown can restore it
# if something rewrites it despite our configuration.
if [[ -r "$HOST_CDI_SPEC" ]]; then
  sudo -n sha256sum "$HOST_CDI_SPEC" 2>/dev/null | awk '{print $1}' > "${OUTDIR}/host-cdi.sha256"
  [[ "$PHASE" == pre ]] && sudo -n cat "$HOST_CDI_SPEC" > "${OUTDIR}/host-cdi.yaml" 2>/dev/null
fi
# Every CDI spec present, so a new one we introduce is visible as drift.
find /var/run/cdi /etc/cdi -maxdepth 1 -type f 2>/dev/null | sort > "${OUTDIR}/cdi-specs.txt"

cap nvidia-smi.txt nvidia-smi
nvidia-smi -q 2>/dev/null \
  | awk '/^[[:space:]]+Fabric$/{f=1;next} f&&/^[[:space:]]+State[[:space:]]*:/{print "fabric_state="$NF; f=0}' \
  | sort -u > "${OUTDIR}/fabric.txt"
nvidia-smi -q 2>/dev/null | awk '/CliqueId/{print "clique="$NF}' | sort -u >> "${OUTDIR}/fabric.txt"
nvidia-smi --query-gpu=driver_version,count --format=csv,noheader 2>/dev/null \
  | head -1 > "${OUTDIR}/driver.txt"

# ---------------------------------------------------------------- filesystem
# Paths we create. Anything here in "post" is a leftover.
# /opt/cni/bin and /etc/cni/net.d are containerd's DEFAULT CNI paths, which k3s
# deliberately leaves alone when --flannel-backend=none so a third-party CNI can
# drop in. Cilium writes to both, so both must be tracked and removed.
{ for p in /var/lib/cni /etc/cni /opt/cni /var/lib/kubelet /var/lib/rancher /etc/rancher \
           /run/k3s /run/flannel /run/cilium /opt/k8s-bootstrap "${NODE_LOCAL_DISK}/k3s" \
           "${NODE_LOCAL_DISK}/local-path" /etc/sysctl.d/98-k8s-bootstrap-rail-ra.conf; do
    printf '%s %s\n' "$p" "$([[ -e "$p" ]] && echo present || echo absent)"
  done
} > "${OUTDIR}/paths.txt"

# /usr/local/bin is on PATH ahead of /usr/bin, so a stray symlink here shadows
# host tooling for every other user of the node.
ls -1 /usr/local/bin 2>/dev/null | sort > "${OUTDIR}/usr-local-bin.txt"

cap disk.txt df -h / "$NODE_LOCAL_DISK"

# ---------------------------------------------------------------- kernel
lsmod 2>/dev/null | awk 'NR>1{print $1}' | sort > "${OUTDIR}/modules.txt"
# RDMA netns mode (install-agent.sh may switch it; teardown restores from the pre snapshot).
rdma system 2>/dev/null > "${OUTDIR}/rdma-system.txt" || :
{ for k in net.ipv4.ip_forward net.ipv4.conf.all.forwarding \
           net.bridge.bridge-nf-call-iptables net.netfilter.nf_conntrack_max; do
    printf '%s=%s\n' "$k" "$(sysctl -n "$k" 2>/dev/null || echo unset)"
  done
} > "${OUTDIR}/sysctl.txt"
# eBPF programs pinned by Cilium live here and must be gone after teardown.
# NEEDS sudo: /sys/fs/bpf is root-only, so a plain `ls` returns permission-denied
# and records an empty file in BOTH phases -- a check that silently does nothing.
sudo -n find /sys/fs/bpf -maxdepth 3 2>/dev/null | sort > "${OUTDIR}/bpf.txt" || :

printf 'snapshot(%s) written to %s\n' "$PHASE" "$OUTDIR"
