#!/usr/bin/env bash
# node/install-imex-cdi.sh -- give containers access to the IMEX channel. RUNS ON A NODE.
#
# Path A needs pods to open /dev/nvidia-caps-imex-channels/channelN so NCCL can
# use the host's multi-node NVLink domain. A hostPath mount is NOT enough: the
# device node appears in the container but cgroup v2's device controller still
# denies open(), and NCCL reports
#   "MNNVL (cliqueSize N) is available but not working on this system"
# Verified: the identical job works with privileged: true and reaches 544 GB/s
# over P2P/MNNVL, so the channel itself is fine -- only authorization was missing.
#
# NVIDIA_IMEX_CHANNELS does not help either, because the GPU Operator runs with
# cdi.enabled=true and CDI injection bypasses the legacy env-var hook.
#
# So we add our OWN CDI spec, which is the documented way to inject a device
# together with its cgroup permission. It is a separate file and never touches the
# host's /var/run/cdi/nvidia.yaml (CLAUDE.md rule 5); node/teardown.sh removes
# files matching k8s-bootstrap-*.
#
# Pods then request it with an annotation:
#   cdi.k8s.io/imex: nvidia.com/imex-channel=all

set -euo pipefail
SPEC_DIR="${CDI_SPEC_DIR:-/var/run/cdi}"
SPEC="${SPEC_DIR}/k8s-bootstrap-imex.yaml"
CHANNEL_DIR="${IMEX_CHANNEL_DIR:-/dev/nvidia-caps-imex-channels}"

log() { printf '[imex-cdi] %s\n' "$*"; }
[[ "$(id -u)" == 0 ]] || exec sudo -E bash "$0" "$@"

[[ -d "$CHANNEL_DIR" ]] || { log "no ${CHANNEL_DIR}; is nvidia-imex running?"; exit 1; }
mapfile -t channels < <(find "$CHANNEL_DIR" -maxdepth 1 -name 'channel*' -printf '%f\n' | sort)
(( ${#channels[@]} )) || { log "no channels under ${CHANNEL_DIR}"; exit 1; }

mkdir -p "$SPEC_DIR"
{
  printf 'cdiVersion: "0.6.0"\n'
  printf 'kind: "nvidia.com/imex-channel"\n'
  printf '# Generated by k8s_bootstrap (node/install-imex-cdi.sh). Additive: the\n'
  printf '# host-generated nvidia.yaml is never modified.\n'
  printf 'devices:\n'
  for c in "${channels[@]}"; do
    printf '  - name: "%s"\n' "$c"
    printf '    containerEdits:\n'
    printf '      deviceNodes:\n'
    printf '        - path: "%s/%s"\n' "$CHANNEL_DIR" "$c"
    printf '          type: c\n'
    printf '          permissions: "rw"\n'
  done
  # An "all" device so a pod can ask for every channel without knowing the count.
  printf '  - name: "all"\n'
  printf '    containerEdits:\n'
  printf '      deviceNodes:\n'
  for c in "${channels[@]}"; do
    printf '        - path: "%s/%s"\n' "$CHANNEL_DIR" "$c"
    printf '          type: c\n'
    printf '          permissions: "rw"\n'
  done
} > "${SPEC}.tmp"
mv "${SPEC}.tmp" "$SPEC"
chmod 0644 "$SPEC"
log "wrote ${SPEC} with channels: ${channels[*]} (+ 'all')"

# Never leave the host spec disturbed.
if [[ -e "${SPEC_DIR}/nvidia.yaml" ]]; then
  log "host CDI spec sha256: $(sha256sum "${SPEC_DIR}/nvidia.yaml" | cut -c1-16)... (unmodified)"
fi
