#!/usr/bin/env bash
# node/install-containerd-cdi-annotations.sh -- let the nvidia runtime see
# cdi.k8s.io/* annotations. RUNS ON A LEASED NODE.
#
# THIS TOUCHES K3S's CONTAINERD, NOT THE HOST'S. CLAUDE.md rule 3 forbids editing
# /etc/containerd/config.toml, which Slurm users share via enroot/pyxis. k3s runs
# its own containerd with its own config under $K3S_DATA_DIR, and it is removed
# wholesale by teardown. Nothing here is visible to any other user of the node.
#
# WHY THIS IS NEEDED
# The host's /etc/nvidia-container-runtime/config.toml already has
#   annotation-prefixes = ["cdi.k8s.io/"]
#   spec-dirs = ["/etc/cdi", "/var/run/cdi"]
# so the nvidia runtime is willing to inject a CDI device named by a pod
# annotation. But containerd only forwards annotations to the OCI runtime when
# they are allowlisted in container_annotations/pod_annotations, and that list is
# empty by default -- so the annotation never reached the runtime and the IMEX
# channel was silently not injected.
#
# k3s's generated config.toml contains
#   imports = ["<data-dir>/agent/etc/containerd/config-v3.toml.d/*.toml"]
# which is the supported drop-in path, so we add a fragment rather than editing
# the generated file (which says DO NOT EDIT).

set -euo pipefail
K3S_DATA_DIR="${K3S_DATA_DIR:-/mnt/localdisk/k3s}"
DROPIN_DIR="${K3S_DATA_DIR}/agent/etc/containerd/config-v3.toml.d"
DROPIN="${DROPIN_DIR}/99-k8s-bootstrap-cdi-annotations.toml"
NVIDIA_RUNTIME="${NVIDIA_RUNTIME:-/usr/bin/nvidia-container-runtime}"

log() { printf '[containerd-cdi] %s\n' "$*"; }
[[ "$(id -u)" == 0 ]] || exec sudo -E bash "$0" "$@"

[[ -d "${K3S_DATA_DIR}/agent/etc/containerd" ]] \
  || { log "no k3s containerd dir at ${K3S_DATA_DIR}; is the agent installed?"; exit 1; }
mkdir -p "$DROPIN_DIR"

# The whole runtime table is restated, not just the annotation keys: a partial
# table in a drop-in risks losing BinaryName/runtime_type depending on how the
# imports merge, which would break GPU containers entirely.
cat > "${DROPIN}.tmp" <<TOML
# Generated by k8s_bootstrap (node/install-containerd-cdi-annotations.sh).
# Allowlists cdi.k8s.io/* so the nvidia runtime can act on CDI device requests
# made via pod annotations -- needed for IMEX channel injection (Path A).
version = 3

[plugins.'io.containerd.cri.v1.runtime'.containerd.runtimes.'nvidia']
  runtime_type = "io.containerd.runc.v2"
  container_annotations = ["cdi.k8s.io/*"]
  pod_annotations = ["cdi.k8s.io/*"]

[plugins.'io.containerd.cri.v1.runtime'.containerd.runtimes.'nvidia'.options]
  BinaryName = "${NVIDIA_RUNTIME}"
  SystemdCgroup = true
TOML
mv "${DROPIN}.tmp" "$DROPIN"
log "wrote ${DROPIN}"

# k3s reads containerd config at startup, so the agent has to be restarted.
for unit in k3s-agent k3s; do
  if systemctl is-active --quiet "$unit" 2>/dev/null; then
    log "restarting ${unit} so containerd re-reads its config"
    systemctl restart "$unit"
    for i in $(seq 1 60); do
      systemctl is-active --quiet "$unit" && break
      sleep 2
    done
    log "${unit} is $(systemctl is-active "$unit")"
    break
  fi
done
log "done"
