"""results/SUMMARY.md and the README results block."""

from __future__ import annotations

import os
import re

import pandas as pd

START, END = "<!-- results:start -->", "<!-- results:end -->"


def _md(df: pd.DataFrame | None, floatfmt: str = ".1f") -> str:
    if df is None or df.empty:
        return "_no data yet_"
    return df.to_markdown(index=False, floatfmt=floatfmt)


def build_summary(
    tables: dict[str, pd.DataFrame], charts: dict[str, str], out: str, index: pd.DataFrame | None = None
) -> str:
    lines = [
        "# Results summary",
        "",
        "Generated by `python -m analysis` from `results/raw/*/result.json`. Every number below is machine-derived; the raw JSON and per-rank CSVs are the source of truth.",
        "",
    ]
    if index is not None and not index.empty:
        fallbacks = int(((index.transport.isin(["nvlink", "rdma"])) & (index.net_socket_channels > 0)).sum())
        lines += [
            f"**Runs:** {len(index)} · all validated: {bool(index['all_ok'].all())} · silent TCP fallbacks on fabric runs: {fallbacks}",
            "",
        ]
    sections = [
        (
            "e1_size_vs_transport",
            "E1 — all-reduce bus bandwidth (GB/s) by message size and transport",
            "size_vs_busbw",
        ),
        (
            "e1_small_latency",
            "E1 — small-message all-reduce time (µs): the latency floor",
            "small_message_latency",
        ),
        ("e2_rails", "E2 — RDMA path: bus bandwidth (GB/s) vs rails claimed per tray", "rails_vs_busbw"),
        ("e3_scaling", "E3 — DDP workload scaling", "scaling_efficiency"),
        (
            "e4_before_after",
            "E4 — optimization: NCCL_IB_QPS_PER_CONNECTION (before → after, 5 repeats)",
            "before_after_box",
        ),
        ("e5_sensitivity", "E5 — sensitivity appendix (bus bandwidth GB/s)", None),
        ("e5_ddp_bucket", "E5 — DDP bucket size on the RDMA path (communication frequency)", None),
        (
            "e5_counters",
            "Counter windows — what the rails, NVLink and PCIe did during a sustained 4 GiB all-reduce",
            None,
        ),
    ]
    for key, title, chart in sections:
        lines += [f"## {title}", ""]
        if chart and chart in charts:
            lines += [
                f"![{title}]({os.path.relpath(charts[chart], os.path.dirname(os.path.abspath(out)))})",
                "",
            ]
        lines += [_md(tables.get(key)), ""]
    text = "\n".join(lines)
    os.makedirs(os.path.dirname(os.path.abspath(out)), exist_ok=True)
    with open(out, "w") as f:
        f.write(text)
    return text


def update_readme(summary_md: str, readme_path: str) -> None:
    if not os.path.exists(readme_path):
        return
    src = open(readme_path).read()
    block = f"{START}\n{summary_md}\n{END}"
    if START in src and END in src:
        src = re.sub(re.escape(START) + r".*?" + re.escape(END), lambda _m: block, src, flags=re.S)
    else:
        src = src.rstrip("\n") + "\n\n" + block + "\n"
    with open(readme_path, "w") as f:
        f.write(src)
